# Generated by Django 3.0.5 on 2020-09-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leave_application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=10)),
                ('e_name', models.CharField(max_length=30)),
                ('e_desig', models.CharField(max_length=30)),
                ('e_application', models.CharField(max_length=500)),
                ('f_date', models.DateTimeField(verbose_name='date published')),
                ('t_date', models.DateTimeField(verbose_name='date published')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_pwd', models.CharField(max_length=30)),
                ('u_type', models.CharField(max_length=10)),
            ],
        ),
    ]
